[package]
name = "ike-render"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# ike
ike-core = { version = "0.0.1", path = "../ike-core" }
ike-wgpu = { version = "0.0.1", path = "../ike-wgpu" }

# other
thiserror = "1.0"
once_cell = "1.8"
