[package]
name = "ike-dylib"
version = "0.1.0-alpha.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["dylib"]

[dependencies]
ike-internal = { path = "../ike-internal", version = "0.1.0-alpha.0" }
