[package]
name = "ike"
version = "0.0.0"
edition = "2018"
description = "Small game engine with a simple editor"
resolver = "2"
repository = "https://github.com/ChangeCaps/ike"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["ike-derive", "ike-editor", "ike-wgpu"]

[dependencies]
anyhow = "^1.0"
egui = "^0.13"
glam = "^0.17"
pollster = "0.2.4"
wgpu = "^0.10"
winit = { version = "^0.25", features = ["serde"] }
ike-derive = { version = "0.0.0", path = "ike-derive" }
image = { version = "^0.23", optional = true }
bytemuck = { version = "^1.7", features = ["derive"] }

[dev-dependencies]
log = "^0.4"
simple_logger = "^1.13"

[features]
default = ["editor", "3d", "2d", "runner"]
runner = []
editor = []
3d = ["image"]
2d = ["image"]
