[package]
name = "ike"
version = "0.0.1"
edition = "2021"
description = "Small game engine with a simple editor"
repository = "https://github.com/ChangeCaps/ike"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["crates/*", "ike-editor"]

[dependencies]

