[package]
name = "ike"
version = "0.0.1"
edition = "2021"
description = "Small game engine with a simple editor"
repository = "https://github.com/ChangeCaps/ike"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["crates/*"]

[dependencies]
# ike
ike-assets = { version = "0.0.1", path = "crates/ike-assets" }
ike-core = { version = "0.0.1", path = "crates/ike-core" }
ike-debug-line = { version = "0.0.1", path = "crates/ike-debug-line" }
ike-input = { version = "0.0.1", path = "crates/ike-input" }
ike-pbr = { version = "0.0.1", path = "crates/ike-pbr" }
ike-render = { version = "0.0.1", path = "crates/ike-render" }
ike-transform = { version = "0.0.1", path = "crates/ike-transform" }
ike-winit = { version = "0.0.1", path = "crates/ike-winit" }
ike-wgpu = { version = "0.0.1", path = "crates/ike-wgpu" }

# other
glam = "0.19"

[dev-dependencies]
# ike
ike-egui = { version = "0.0.1", path = "crates/ike-egui" }

# other
env_logger = "0.9"