[package]
name = "ike-core"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8"
rayon = "1.5"
serde = { version = "1.0", features = ["derive"] } 