[package]
name = "ike-wgpu"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu-types = "^0.10"
wgpu = { version = "^0.10", optional = true }