[package]
name = "ike-winit"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# ike
ike-core = { version = "0.0.1", path = "../ike-core" }
ike-input = { version = "0.0.1", path = "../ike-input" }
ike-render = { version = "0.0.1", path = "../ike-render" }
ike-wgpu = { version = "0.0.1", path = "../ike-wgpu", features = ["wgpu"] }

# other
anyhow = "1.0"
glam = "0.19"
pollster = "0.2"
wgpu = "0.11"
winit = "0.25"